version: '3'

services:
  myflix-mongodb:
    image: mongo
    container_name: myflix-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
      - ./init-scripts:/docker-entrypoint-initdb.d

  myflix-node:
    build:
      context: ./MyFlix-Node
    container_name: myflix-node
    depends_on:
      - myflix-mongodb
    environment:
      MONGODB_URI: "mongodb://yourUsername:yourPassword@myflix-mongodb:27017/myflix"
    ports:
      - "5000:5000"

  myflix-react:
    build:
      context: ./MyFlix-React
    container_name: myflix-react
    env_file:
      - ./init-scripts/.env
    ports:
      - "80:3000"
