name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.testing.DOCKER_USERNAME }}
          password: ${{ secrets.testing.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.testing.DOCKER_USERNAME }}/myflix:latest

      - name: Deploy to AWS
        run: |
          ssh -o StrictHostKeyChecking=no -i $AWS_SSH_KEY ec2-user@$AWS_INSTANCE_IP 'bash -s' < deploy.sh
        env:
          AWS_SSH_KEY: ${{ secrets.testing.AWS_SSH_KEY }}
          AWS_INSTANCE_IP: ${{ secrets.testing.AWS_INSTANCE_IP }}
