name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Extra Repos
        run: |
          git clone https://github.com/euandocking/MyFlix-Node.git
          git clone https://github.com/euandocking/MyFlix-React.git

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Docker Compose Action
        uses: isbang/compose-action@v1.5.1
      
      - name: Build and Push Docker Images
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker-compose build
          docker-compose push
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Deploy to AWS
        run: |
          ssh -o StrictHostKeyChecking=no -i $AWS_SSH_KEY ec2-user@$AWS_INSTANCE_IP 'bash -s' < deploy.sh
        env:
          AWS_SSH_KEY: ${{ secrets.AWS_SSH_KEY }}
          AWS_INSTANCE_IP: ${{ secrets.AWS_INSTANCE_IP }}
